USE [master]
GO

/****** Object:  Database [mi primera vez]    Script Date: 14/08/2025 11:44:59 ******/
CREATE DATABASE [mi primera vez]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'mi primera vez', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\mi primera vez.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'mi primera vez_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\mi primera vez_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [mi primera vez].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [mi primera vez] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [mi primera vez] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [mi primera vez] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [mi primera vez] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [mi primera vez] SET ARITHABORT OFF 
GO

ALTER DATABASE [mi primera vez] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [mi primera vez] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [mi primera vez] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [mi primera vez] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [mi primera vez] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [mi primera vez] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [mi primera vez] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [mi primera vez] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [mi primera vez] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [mi primera vez] SET  DISABLE_BROKER 
GO

ALTER DATABASE [mi primera vez] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [mi primera vez] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [mi primera vez] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [mi primera vez] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [mi primera vez] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [mi primera vez] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [mi primera vez] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [mi primera vez] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [mi primera vez] SET  MULTI_USER 
GO

ALTER DATABASE [mi primera vez] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [mi primera vez] SET DB_CHAINING OFF 
GO

ALTER DATABASE [mi primera vez] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [mi primera vez] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO


